=== AnweshDahal/l5-eppt-cw2/catalog_19030735.dtd
<!ELEMENT audioArch (storeInfo, songs, footer)>

<!ELEMENT storeInfo (storeLogo, storeName, storeAddress, storeContact, storeWebsite, storeEmail, storeDetails)>

<!ELEMENT storeLogo EMPTY>
<!ELEMENT storeName (#PCDATA)>
<!ELEMENT storeAddress (#PCDATA)>
<!ELEMENT storeContact (#PCDATA)>
<!ELEMENT storeWebsite (#PCDATA)>
<!ELEMENT storeEmail (#PCDATA)>
<!ELEMENT storeDetails (#PCDATA)>

<!ELEMENT songs (song+)>

<!ELEMENT song (albumImage, songTitle, artist, featuredArtist?, album, year, genre, director?, producer?, length, writers, award?, studio?, rLabel)>
<!ELEMENT albumImage EMPTY>
<!ELEMENT songTitle (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT featuredArtist (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT writers (writer+)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT award (#PCDATA)>
<!ELEMENT studio (#PCDATA)>
<!ELEMENT rLabel (#PCDATA)>

<!ELEMENT footer (#PCDATA)>

<!ATTLIST song song_id ID #REQUIRED format (digital|physical) #REQUIRED language CDATA #IMPLIED rating CDATA #REQUIRED price CDATA #REQUIRED>
<!ATTLIST studio location CDATA #IMPLIED>

=== AnweshDahal/l5-eppt-cw2/catalog_19030735.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="catalog_19030735.css"?>

<!-- 
  Name: Anwesh Dahal
  University ID: 19030735
  Date: April 12 2021
 -->

<!DOCTYPE audioArch SYSTEM "catalog_19030735.dtd">
 
<audioArch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema">
  <storeInfo>
    <storeLogo/>
    <storeName>Clausia Audio Arch</storeName>
    <storeAddress>Petal St., Nublar, Clausia</storeAddress>
    <storeContact>021-536669</storeContact>
    <storeWebsite>www.audioarch.clausia.com</storeWebsite>
    <storeEmail>contact@audioarch.clausia.com</storeEmail>
    <storeDetails>Clausia Audio Arch is your go to place to shop for Electronic and New Wave music from the 80s and 90s</storeDetails>
  </storeInfo>

  <songs>
    <song song_id="s01" format="physical" rating="5" price="100.00" language="en">
      <albumImage/>
      <songTitle>Blue Monday</songTitle>
      <artist>New Order</artist>
      <album>Substance</album>
      <year>1987</year>
      <genre>Rock</genre>
      <director>Robert Breer</director>
      <length>7:29</length>
      <writers>
        <writer>Gillian Gilbert</writer>
        <writer>Peter Hook</writer>
        <writer>Stephen Morris</writer>
        <writer>Bernard Summer</writer>
      </writers>
      <award>NME Award for Best Single</award>
      <rLabel>Factory</rLabel>
    </song>

    <song song_id="s02" format="digital" rating="5" price="60.00" language="en">
      <albumImage />
      <songTitle>Disappointed</songTitle>
      <artist>Electronic</artist>
      <album>Cool World</album>
      <year>1992</year>
      <genre>Pop</genre>
      <director>Howard Greenhalgh</director>
      <length>4:39</length>
      <writers>
        <writer>Bernard Summer</writer>
        <writer>Jhonny Marr</writer>
        <writer>Neil Tennant</writer>
      </writers>
      <rLabel>Parlophone</rLabel>
    </song>
    <song song_id="s03" format="digital" rating="5" price="90.00" language="en">
      <albumImage />
      <songTitle>True Faith</songTitle>
      <artist>New Order</artist>
      <album>Substance</album>
      <year>1987</year>
      <genre>Pop</genre>
      <director>Philippe Decoufle</director>
      <producer>Stephen Hauge</producer>
      <length>5:53</length>
      <writers>
        <writer>Gillian Gilbert</writer>
        <writer>Peter Hook</writer>
        <writer>Stephen Morris</writer>
        <writer>Bernard Summer</writer>
      </writers>
      <rLabel>Factory</rLabel>
    </song>
    <song song_id="s04" format="physical" rating="5" price="80.00" language="en">
      <albumImage />
      <songTitle>Heart</songTitle>
      <artist>Pet Shop Boys</artist>
      <album>Actually</album>
      <year>1987</year>
      <genre>Pop</genre>
      <director>Jack Bond</director>
      <producer>Andy Richards</producer>
      <length>4:16</length>
      <writers>
        <writer>Neil Tennant</writer>
        <writer>Chris Lowe</writer>
      </writers>
      <rLabel>Parlophone</rLabel>
    </song>
    <song song_id="s05" format="physical" rating="5" price="69.00" language="en">
      <albumImage />
      <songTitle>Relax</songTitle>
      <artist>Frankie Goes to Hollywood</artist>
      <album>Welcome to the Pleasuredome</album>
      <year>1984</year>
      <genre>New Wave</genre>
      <director>Bernard Rose</director>
      <producer>Trevor Horn</producer>
      <length>3:53</length>
      <writers>
        <writer>Peter Gill</writer>
        <writer>Holly Johnson</writer>
        <writer>Brian Nash</writer>
        <writer>Mark O'Toole</writer>
      </writers>
      <award>NME Award for Best Single</award>
      <rLabel>ZTT</rLabel>
    </song>
    <song song_id="s06" format="digital" rating="5" price="71.89">
      <albumImage />
      <songTitle>Dayvan Cowboy</songTitle>
      <artist>Boards of Canada</artist>
      <album>The Campfire headphase</album>
      <year>2005</year>
      <genre>Electronic</genre>
      <director>Melissa Olson</director>
      <length>4:36</length>
      <writers>
        <writer>Michael Sandison</writer>
        <writer>Marcus Sandison</writer>
      </writers>
      <rLabel>Warp</rLabel>
    </song>
    <song song_id="s07" format="physical" rating="4" price="80.30" language="en">
      <albumImage />
      <songTitle>What Have I Done To Deserve This</songTitle>
      <artist>Pet Shop Boys</artist>
      <featuredArtist>Dusty Springfeild</featuredArtist>
      <album>Actually</album>
      <year>1986</year>
      <genre>Synth-pop</genre>
      <director>Eric Watsib</director>
      <producer>Stephen Hauge</producer>
      <length>4:19</length>
      <writers>
        <writer>Chris Lowe</writer>
        <writer>Neil Tennant</writer>
        <writer>Allee Willis</writer>
      </writers>
      <studio>Sarm West</studio>
      <rLabel>Parlophone</rLabel>
    </song>
    <song song_id="s08" format="physical" rating="4" price="50.00" language="en">
      <albumImage />
      <songTitle>All the Things She Said</songTitle>
      <artist>Simple Minds</artist>
      <featuredArtist>Robin Clark</featuredArtist>
      <album>Once Upon a Time</album>
      <year>1986</year>
      <genre>New Wave</genre>
      <director>Jimmy Lovine</director>
      <length>4:15</length>
      <writers>
        <writer>Jim Kerr</writer>
        <writer>Cahrlie Burchill</writer>
        <writer>Mick MacNeil</writer>
      </writers>
      <rLabel>Virgin</rLabel>
    </song>
    <song song_id="s09" format="digital" rating="5" price="80.00" language="en">
      <albumImage />
      <songTitle>Music Sounds Better With You</songTitle>
      <artist>Stardust</artist>
      <album>Music So</album>
      <year>1998</year>
      <genre>Electronic</genre>
      <director>Michel Gondry</director>
      <producer>Stardust</producer>
      <length>6:48</length>
      <writers>
        <writer>Thomas Bangalter</writer>
        <writer>Alan Queme</writer>
      </writers>
      <award>DJ Award for track of the Season</award>
      <studio location="france">Daft House</studio>
      <rLabel>Virgin</rLabel>
    </song>
  </songs>
  <footer>&#169; 1993-2021 Clausia Audio Arch</footer>
</audioArch>
